{
 "title": "k8s-argo-rollout",
 "description": "Dashboard for Kubernetes Deployment with Prometheus.",
 "tags": [
  "kubernetes",
  "prometheus",
  "intergrated"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_namespace_labels,namespace)"
    }
   },
   {
    "name": "rollout",
    "query": {
     "query": "label_values(rollout_info{namespace =~\"^$namespace$\"},name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Istio Workload",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Response Size By Destination",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(irate(istio_response_bytes_bucket{reporter=\"source\", connection_security_policy!=\"mutual_tls\", source_workload!=\"\", source_workload_namespace=~\"$namespace\", destination_service!=\"\"}[1m])) by (destination_service, le))",
     "legendFormat": "{{ destination_service }} P50"
    }
   ]
  },
  {
   "title": "Outgoing Success Rate (non-5xx responses) By Destination",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(istio_requests_total{reporter=\"source\", connection_security_policy!=\"mutual_tls\", source_workload_namespace=~\"$namespace\", response_code!~\"5.*\"}[1m])) by (destination_service) / sum(irate(istio_requests_total{reporter=\"source\", connection_security_policy!=\"mutual_tls\", source_workload_namespace=~\"$namespace\"}[1m])) by (destination_service)",
     "legendFormat": "{{ destination_service }}"
    }
   ]
  },
  { "title": "Istio Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Bytes Received from Incoming TCP Connection",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "round(sum(irate(istio_tcp_received_bytes_total{reporter=\"destination\", connection_security_policy=\"mutual_tls\", destination_workload_namespace=~\"$namespace\"}[1m])) by (destination_workload, destination_workload_namespace), 0.001)",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace}} (?mTLS)"
    },
    {
     "expr": "round(sum(irate(istio_tcp_received_bytes_total{reporter=\"destination\", connection_security_policy!=\"mutual_tls\",destination_workload_namespace=~\"$namespace\"}[1m])) by (destination_workload, destination_workload_namespace), 0.001)",
     "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace}}"
    }
   ]
  },
  {
   "title": "Bytes Sent to Incoming TCP Connection",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "round(sum(irate(istio_tcp_sent_bytes_total{connection_security_policy=\"mutual_tls\", reporter=\"destination\", destination_workload_namespace=~\"$namespace\"}[1m])) by (destination_workload, destination_workload_namespace), 0.001)",
     "legendFormat": "{{ destination_workload }}.{{destination_workload_namespace }} (?mTLS)"
    },
    {
     "expr": "round(sum(irate(istio_tcp_sent_bytes_total{connection_security_policy!=\"mutual_tls\", reporter=\"destination\",destination_workload_namespace=~\"$namespace\"}[1m])) by (destination_workload, destination_workload_namespace), 0.001)",
     "legendFormat": "{{ destination_workload }}.{{destination_workload_namespace }}"
    }
   ]
  },
  { "title": "Istio Mesh", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 }, "repeat": "datasource" },
  {
   "title": "Global Request Volume",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "round(sum(irate(istio_requests_total{pod=~\"^$rollout-[a-z0-9]+-[a-z0-9]+\", namespace=\"$namespace\",reporter=\"source\"}[1m])), 0.001)"
    }
   ]
  },
  {
   "title": "Global Success Rate (non-5xx responses)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total{namespace=\"$namespace\", pod=~\"^$rollout-[a-z0-9]+-[a-z0-9]+\", reporter=\"source\", response_code!~\"5.*\"}[1m])) / sum(rate(istio_requests_total{namespace=\"$namespace\", pod=~\"^$rollout-[a-z0-9]+-[a-z0-9]+\", reporter=\"source\"}[1m]))"
    }
   ]
  },
  {
   "title": "4xxs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(istio_requests_total{destination_workload_namespace=\"$namespace\", reporter=\"source\", response_code=~\"4.*\"}[1m]))"
    }
   ]
  },
  {
   "title": "5xxs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(istio_requests_total{destination_workload_namespace=\"$namespace\", reporter=\"source\", response_code=~\"5.*\"}[1m]))"
    }
   ]
  },
  { "title": "Pod", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Pods Running",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\",phase=\"Running\"})"
    }
   ]
  },
  {
   "title": "Pods Pending",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 4, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\",phase=\"Pending\"})"
    }
   ]
  },
  {
   "title": "Pods Failed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\",phase=\"Failed\"})"
    }
   ]
  },
  {
   "title": "Pods Unknown",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\",phase=\"Unknown\"})"
    }
   ]
  },
  {
   "title": "Pods Succeeded",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\",phase=\"Succeeded\"})"
    }
   ]
  },
  { "title": "Rollout", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "HPA (current/max)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(kube_horizontalpodautoscaler_status_current_replicas{namespace=~\"^$namespace$\"}/kube_horizontalpodautoscaler_spec_max_replicas{namespace=~\"^$namespace$\"} * 100)"
    },
    {}
   ]
  },
  {
   "title": "CPU Usage / Requests [1m AVG]",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100\n* sum(rate(container_cpu_usage_seconds_total{namespace=~\"^$namespace$\",pod=~\"^$rollout-[a-z0-9]+-[a-z0-9]+\",container!~\"POD|\"}[1m]))\n/ sum(kube_pod_container_resource_requests{resource=~\"cpu\",namespace=~\"^$namespace$\",pod=~\"^$rollout-[a-z0-9]+-[a-z0-9]+\"})"
    }
   ]
  },
  {
   "title": "CPU Usage (1m avg)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"^$namespace$\",pod=~\"^$rollout-[a-z0-9]+-[a-z0-9]+\",container!~\"POD|\"}[1m])) by (pod)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "CPU Throttled (1m avg)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "100\n* sum by(pod, namespace) (increase(container_cpu_cfs_throttled_periods_total{namespace=~\"^$namespace$\",pod=~\"^$rollout-[a-z0-9]+-[a-z0-9]+\",container!~\"POD|\"}[1m]))\n/ sum by(pod, namespace) (increase(container_cpu_cfs_periods_total{namespace=~\"^$namespace$\",pod=~\"^$rollout-[a-z0-9]+-[a-z0-9]+\",container!~\"POD|\"}[1m]))",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "HPA MIN",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(kube_horizontalpodautoscaler_spec_min_replicas{namespace=~\"^$namespace$\"})"
    }
   ]
  },
  {
   "title": "HPA MAX",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(kube_horizontalpodautoscaler_spec_max_replicas{namespace=~\"^$namespace$\"})"
    }
   ]
  },
  {
   "title": "Usage",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"^$namespace$\",pod=~\"^$rollout-[a-z0-9]+-[a-z0-9]+\",container!~\"POD|\"}[2m]))"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=~\"^$namespace$\",pod=~\"^$rollout-[a-z0-9]+-[a-z0-9]+\",resource=\"cpu\"})"
    }
   ]
  },
  {
   "title": "Limits",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=~\"^$namespace$\",pod=~\"^$rollout-[a-z0-9]+-[a-z0-9]+\",resource=\"cpu\"})"
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rollout_info_replicas_available{namespace=~\"^$namespace$\",name=~\"^$rollout\"})",
     "legendFormat": "Available"
    },
    {
     "expr": "sum(rollout_info_replicas_unavailable{namespace=~\"^$namespace$\",name=~\"^$rollout\"})",
     "legendFormat": "Unavailable"
    }
   ]
  },
  {
   "title": "Memory Usage / Requests",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=~\"^$namespace$\",pod=~\"^$rollout-[a-z0-9]+-[a-z0-9]+\",container!~\"POD|\"}) / sum (kube_pod_container_resource_requests{resource=~\"memory\",namespace=~\"^$namespace$\",pod=~\"^$rollout-[a-z0-9]+-[a-z0-9]+\"}) * 100"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=~\"^$namespace$\",pod=~\"^$rollout-[a-z0-9]+-[a-z0-9]+\",container!~\"POD|\"}) by (pod)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Network I/O Total (1m avg)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{namespace=~\"^$namespace$\",pod=~\"^$rollout-[a-z0-9]+-[a-z0-9]+\"}[1m]))",
     "legendFormat": "receive"
    },
    {
     "expr": "- sum(irate(container_network_transmit_bytes_total{namespace=~\"^$namespace$\",pod=~\"^$rollout-[a-z0-9]+-[a-z0-9]+\"}[1m]))",
     "legendFormat": "transmit"
    }
   ]
  },
  {
   "title": "Available",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rollout_info_replicas_available{namespace=~\"^$namespace$\",name=~\"^$rollout\"})"
    }
   ]
  },
  {
   "title": "Unavailable",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rollout_info_replicas_unavailable{namespace=~\"^$namespace$\",name=~\"^$rollout\"})"
    }
   ]
  },
  {
   "title": "Usage",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=~\"^$namespace$\",pod=~\"^$rollout-[a-z0-9]+-[a-z0-9]+\",container!~\"POD|\"})"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=~\"^$namespace$\",pod=~\"^$rollout-[a-z0-9]+-[a-z0-9]+\",resource=\"memory\"})"
    }
   ]
  },
  {
   "title": "Limits",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=~\"^$namespace$\",pod=~\"^$rollout-[a-z0-9]+-[a-z0-9]+\",resource=\"memory\"})"
    }
   ]
  },
  {
   "title": "Container",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "Container CPU Usage (1m avg)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"^$namespace$\", container!=\"\"}[1m])) by (container, pod)",
       "legendFormat": "{{ pod }} | {{ container }}"
      }
     ]
    },
    {
     "title": "Container Memory Usage (1m avg)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{namespace=~\"^$namespace$\",pod=~\"^$rollout-[a-z0-9]+-[a-z0-9]+\",container!~\"\"}) by (container, pod)",
       "legendFormat": "{{ pod }} | {{ container }}"
      }
     ]
    },
    {
     "title": "CPU Requests & Limit",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "core" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by (container) (kube_pod_container_resource_requests{namespace=~\"^$namespace$\",pod=~\"^$rollout-[a-z0-9]+-[a-z0-9]+\",resource=\"cpu\"})",
       "legendFormat": "[REQ]-{{container}}"
      },
      {
       "expr": "avg by (container) (kube_pod_container_resource_limits{namespace=~\"^$namespace$\",pod=~\"^$rollout-[a-z0-9]+-[a-z0-9]+\",resource=\"cpu\"})",
       "legendFormat": "[LIM]-{{container}}"
      }
     ]
    },
    {
     "title": "Memory Requests & Limit",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by (container)(kube_pod_container_resource_requests{namespace=~\"^$namespace$\",pod=~\"^$rollout-[a-z0-9]+-[a-z0-9]+\",resource=\"memory\"})",
       "legendFormat": "[REQ]-{{container}}"
      },
      {
       "expr": "avg by (container)(kube_pod_container_resource_limits{namespace=~\"^$namespace$\",pod=~\"^$rollout-[a-z0-9]+-[a-z0-9]+\",resource=\"memory\"})",
       "legendFormat": "[LIM]-{{container}}"
      }
     ]
    }
   ]
  }
 ]
}