
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: SLO
    app.kubernetes.io/managed-by: sloth
    release: prometheus
  name: sloth-slo-java-app-latency
  namespace: monitoring
spec:
  groups:
  - name: sloth-slo-sli-recordings-java-demo-app-requests-latency
    rules:
    - expr: |
        ((
          sum(rate(istio_request_duration_milliseconds_count{app=~"java-demo|java-demo-auto"}[5m]))
          -
          sum(rate(istio_request_duration_milliseconds_bucket{le="250",app=~"java-demo|java-demo-auto"}[5m]))
        )
        )
        /
        (sum(rate(istio_request_duration_milliseconds_count{app=~"java-demo|java-demo-auto"}[5m])))
      labels:
        owner: yunusgun
        repo: myorg/java-demo-app
        sloth_id: java-demo-app-requests-latency
        sloth_service: java-demo-app
        sloth_slo: requests-latency
        sloth_window: 5m
        tier: "2"
      record: slo:sli_error:ratio_rate5m
    - expr: |
        ((
          sum(rate(istio_request_duration_milliseconds_count{app=~"java-demo|java-demo-auto"}[30m]))
          -
          sum(rate(istio_request_duration_milliseconds_bucket{le="250",app=~"java-demo|java-demo-auto"}[30m]))
        )
        )
        /
        (sum(rate(istio_request_duration_milliseconds_count{app=~"java-demo|java-demo-auto"}[30m])))
      labels:
        owner: yunusgun
        repo: myorg/java-demo-app
        sloth_id: java-demo-app-requests-latency
        sloth_service: java-demo-app
        sloth_slo: requests-latency
        sloth_window: 30m
        tier: "2"
      record: slo:sli_error:ratio_rate30m
    - expr: |
        ((
          sum(rate(istio_request_duration_milliseconds_count{app=~"java-demo|java-demo-auto"}[1h]))
          -
          sum(rate(istio_request_duration_milliseconds_bucket{le="250",app=~"java-demo|java-demo-auto"}[1h]))
        )
        )
        /
        (sum(rate(istio_request_duration_milliseconds_count{app=~"java-demo|java-demo-auto"}[1h])))
      labels:
        owner: yunusgun
        repo: myorg/java-demo-app
        sloth_id: java-demo-app-requests-latency
        sloth_service: java-demo-app
        sloth_slo: requests-latency
        sloth_window: 1h
        tier: "2"
      record: slo:sli_error:ratio_rate1h
    - expr: |
        ((
          sum(rate(istio_request_duration_milliseconds_count{app=~"java-demo|java-demo-auto"}[2h]))
          -
          sum(rate(istio_request_duration_milliseconds_bucket{le="250",app=~"java-demo|java-demo-auto"}[2h]))
        )
        )
        /
        (sum(rate(istio_request_duration_milliseconds_count{app=~"java-demo|java-demo-auto"}[2h])))
      labels:
        owner: yunusgun
        repo: myorg/java-demo-app
        sloth_id: java-demo-app-requests-latency
        sloth_service: java-demo-app
        sloth_slo: requests-latency
        sloth_window: 2h
        tier: "2"
      record: slo:sli_error:ratio_rate2h
    - expr: |
        ((
          sum(rate(istio_request_duration_milliseconds_count{app=~"java-demo|java-demo-auto"}[6h]))
          -
          sum(rate(istio_request_duration_milliseconds_bucket{le="250",app=~"java-demo|java-demo-auto"}[6h]))
        )
        )
        /
        (sum(rate(istio_request_duration_milliseconds_count{app=~"java-demo|java-demo-auto"}[6h])))
      labels:
        owner: yunusgun
        repo: myorg/java-demo-app
        sloth_id: java-demo-app-requests-latency
        sloth_service: java-demo-app
        sloth_slo: requests-latency
        sloth_window: 6h
        tier: "2"
      record: slo:sli_error:ratio_rate6h
    - expr: |
        ((
          sum(rate(istio_request_duration_milliseconds_count{app=~"java-demo|java-demo-auto"}[1d]))
          -
          sum(rate(istio_request_duration_milliseconds_bucket{le="250",app=~"java-demo|java-demo-auto"}[1d]))
        )
        )
        /
        (sum(rate(istio_request_duration_milliseconds_count{app=~"java-demo|java-demo-auto"}[1d])))
      labels:
        owner: yunusgun
        repo: myorg/java-demo-app
        sloth_id: java-demo-app-requests-latency
        sloth_service: java-demo-app
        sloth_slo: requests-latency
        sloth_window: 1d
        tier: "2"
      record: slo:sli_error:ratio_rate1d
    - expr: |
        ((
          sum(rate(istio_request_duration_milliseconds_count{app=~"java-demo|java-demo-auto"}[3d]))
          -
          sum(rate(istio_request_duration_milliseconds_bucket{le="250",app=~"java-demo|java-demo-auto"}[3d]))
        )
        )
        /
        (sum(rate(istio_request_duration_milliseconds_count{app=~"java-demo|java-demo-auto"}[3d])))
      labels:
        owner: yunusgun
        repo: myorg/java-demo-app
        sloth_id: java-demo-app-requests-latency
        sloth_service: java-demo-app
        sloth_slo: requests-latency
        sloth_window: 3d
        tier: "2"
      record: slo:sli_error:ratio_rate3d
    - expr: |
        sum_over_time(slo:sli_error:ratio_rate5m{sloth_id="java-demo-app-requests-latency", sloth_service="java-demo-app", sloth_slo="requests-latency"}[30d])
        / ignoring (sloth_window)
        count_over_time(slo:sli_error:ratio_rate5m{sloth_id="java-demo-app-requests-latency", sloth_service="java-demo-app", sloth_slo="requests-latency"}[30d])
      labels:
        owner: yunusgun
        repo: myorg/java-demo-app
        sloth_id: java-demo-app-requests-latency
        sloth_service: java-demo-app
        sloth_slo: requests-latency
        sloth_window: 30d
        tier: "2"
      record: slo:sli_error:ratio_rate30d
  - name: sloth-slo-meta-recordings-java-demo-app-requests-latency
    rules:
    - expr: vector(0.9990000000000001)
      labels:
        owner: yunusgun
        repo: myorg/java-demo-app
        sloth_id: java-demo-app-requests-latency
        sloth_service: java-demo-app
        sloth_slo: requests-latency
        tier: "2"
      record: slo:objective:ratio
    - expr: vector(1-0.9990000000000001)
      labels:
        owner: yunusgun
        repo: myorg/java-demo-app
        sloth_id: java-demo-app-requests-latency
        sloth_service: java-demo-app
        sloth_slo: requests-latency
        tier: "2"
      record: slo:error_budget:ratio
    - expr: vector(30)
      labels:
        owner: yunusgun
        repo: myorg/java-demo-app
        sloth_id: java-demo-app-requests-latency
        sloth_service: java-demo-app
        sloth_slo: requests-latency
        tier: "2"
      record: slo:time_period:days
    - expr: |
        slo:sli_error:ratio_rate5m{sloth_id="java-demo-app-requests-latency", sloth_service="java-demo-app", sloth_slo="requests-latency"}
        / on(sloth_id, sloth_slo, sloth_service) group_left
        slo:error_budget:ratio{sloth_id="java-demo-app-requests-latency", sloth_service="java-demo-app", sloth_slo="requests-latency"}
      labels:
        owner: yunusgun
        repo: myorg/java-demo-app
        sloth_id: java-demo-app-requests-latency
        sloth_service: java-demo-app
        sloth_slo: requests-latency
        tier: "2"
      record: slo:current_burn_rate:ratio
    - expr: |
        slo:sli_error:ratio_rate30d{sloth_id="java-demo-app-requests-latency", sloth_service="java-demo-app", sloth_slo="requests-latency"}
        / on(sloth_id, sloth_slo, sloth_service) group_left
        slo:error_budget:ratio{sloth_id="java-demo-app-requests-latency", sloth_service="java-demo-app", sloth_slo="requests-latency"}
      labels:
        owner: yunusgun
        repo: myorg/java-demo-app
        sloth_id: java-demo-app-requests-latency
        sloth_service: java-demo-app
        sloth_slo: requests-latency
        tier: "2"
      record: slo:period_burn_rate:ratio
    - expr: 1 - slo:period_burn_rate:ratio{sloth_id="java-demo-app-requests-latency",
        sloth_service="java-demo-app", sloth_slo="requests-latency"}
      labels:
        owner: yunusgun
        repo: myorg/java-demo-app
        sloth_id: java-demo-app-requests-latency
        sloth_service: java-demo-app
        sloth_slo: requests-latency
        tier: "2"
      record: slo:period_error_budget_remaining:ratio
    - expr: vector(1)
      labels:
        owner: yunusgun
        repo: myorg/java-demo-app
        sloth_id: java-demo-app-requests-latency
        sloth_mode: cli-gen-k8s
        sloth_objective: "99.9"
        sloth_service: java-demo-app
        sloth_slo: requests-latency
        sloth_spec: sloth.slok.dev/v1
        sloth_version: 0.11.0
        tier: "2"
      record: sloth_slo_info
  - name: sloth-slo-alerts-java-demo-app-requests-latency
    rules:
    - alert: JavaAppHighErrorRate
      annotations:
        summary: High error rate on 'java-demo-app' requests responses
        title: (page) {{$labels.sloth_service}} {{$labels.sloth_slo}} SLO error budget
          burn rate is too fast.
      expr: |
        (
            max(slo:sli_error:ratio_rate5m{sloth_id="java-demo-app-requests-latency", sloth_service="java-demo-app", sloth_slo="requests-latency"} > (14.4 * 0.0007999999999999432)) without (sloth_window)
            and
            max(slo:sli_error:ratio_rate1h{sloth_id="java-demo-app-requests-latency", sloth_service="java-demo-app", sloth_slo="requests-latency"} > (14.4 * 0.0007999999999999432)) without (sloth_window)
        )
        or
        (
            max(slo:sli_error:ratio_rate30m{sloth_id="java-demo-app-requests-latency", sloth_service="java-demo-app", sloth_slo="requests-latency"} > (6 * 0.0007999999999999432)) without (sloth_window)
            and
            max(slo:sli_error:ratio_rate6h{sloth_id="java-demo-app-requests-latency", sloth_service="java-demo-app", sloth_slo="requests-latency"} > (6 * 0.0007999999999999432)) without (sloth_window)
        )
      labels:
        category: latency
        routing_key: myteam
        severity: pageteam
        sloth_severity: page
    - alert: JavaAppHighErrorRate
      annotations:
        summary: High error rate on 'java-demo-app' requests responses
        title: (ticket) {{$labels.sloth_service}} {{$labels.sloth_slo}} SLO error
          budget burn rate is too fast.
      expr: |
        (
            max(slo:sli_error:ratio_rate2h{sloth_id="java-demo-app-requests-latency", sloth_service="java-demo-app", sloth_slo="requests-latency"} > (3 * 0.0007999999999999432)) without (sloth_window)
            and
            max(slo:sli_error:ratio_rate1d{sloth_id="java-demo-app-requests-latency", sloth_service="java-demo-app", sloth_slo="requests-latency"} > (3 * 0.0007999999999999432)) without (sloth_window)
        )
        or
        (
            max(slo:sli_error:ratio_rate6h{sloth_id="java-demo-app-requests-latency", sloth_service="java-demo-app", sloth_slo="requests-latency"} > (1 * 0.0007999999999999432)) without (sloth_window)
            and
            max(slo:sli_error:ratio_rate3d{sloth_id="java-demo-app-requests-latency", sloth_service="java-demo-app", sloth_slo="requests-latency"} > (1 * 0.0007999999999999432)) without (sloth_window)
        )
      labels:
        category: latency
        severity: warning
        sloth_severity: ticket
