apiVersion: sloth.slok.dev/v1
kind: PrometheusServiceLevel
metadata:
  name: sloth-slo-java-app-availability
  namespace: monitoring
spec:
  service: "java-demo-app"
  labels:
    owner: "yunusgun"
    repo: "myorg/java-demo-app"
    tier: "2"
  slos:
    - name: "requests-availability"
      objective: 99.9
      description: "Common SLO based on availability for HTTP request responses."
      sli:
        plugin:
          id: "sloth-common/istio/v1/availability"
        events:
          errorQuery: sum(rate(istio_request_duration_milliseconds_count{job="myservice",code=~"(5..|429)"}[{{.window}}]))
          totalQuery: sum(rate(istio_request_duration_milliseconds_count{job="myservice"}[{{.window}}]))
      alerting:
        name: JavaAppHighErrorRate
        labels:
          category: "availability"
        annotations:
          summary: "High error rate on 'java-demo-app' requests responses"
        pageAlert:
          labels:
            severity: pageteam
            routing_key: myteam
        ticketAlert:
          labels:
            severity: "warning"

