apiVersion: sloth.slok.dev/v1
kind: PrometheusServiceLevel
metadata:
  name: sloth-slo-java-app-latency
  namespace: monitoring
spec:
  service: "java-demo-app"
  labels:
    owner: "yunusgun"
    repo: "myorg/java-demo-app"
    tier: "2"
  slos:
    - name: "requests-latency"
      objective: 99
      description: "Common SLO based on latency for HTTP request responses."
      labels:
        category: latency
      sli:
        plugin:
          id: "sloth-common/istio/v1/latency"
        events:
        error_query: |
          (
            sum(rate(apiserver_request_duration_seconds_count{verb!="WATCH"}[{{.window}}]))
            -
            sum(rate(apiserver_request_duration_seconds_bucket{le="0.4",verb!="WATCH"}[{{.window}}]))
          )
        total_query: sum(rate(apiserver_request_duration_seconds_count{verb!="WATCH"}[{{.window}}]))
      alerting:
        name: java-demoLatencyAlert
        labels:
          category: "latency"
        page_alert:
          labels:
            severity: critical
        ticket_alert:
          labels:
            severity: warning
