pipeline {
    agent any
    tools {
        maven 'maven-3.9.6' 
        dockerTool 'docker'
    }
    stages {
         stage('Check SCM') {
              steps {
                 git branch: 'dev',
                     credentialsId: 'github-credential',
                     url: 'git@github.com:yunusgun/java-demoapp.git'
              }
         }
         stage('Build Docker Image') {
              steps {
                 sh "docker build -t yunusgun06/java-app-modified:${env.BUILD_NUMBER} -f build/Dockerfile ."
              }
         }
         stage('Login Docker Hub') {
              steps {
                 withCredentials([usernamePassword(credentialsId: 'docker-hub', usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD')]) {
                     sh "docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD"
                 }
              }
         }
         stage('Push Docker Image') {
              steps {
                 sh "docker push yunusgun06/java-app-modified:${env.BUILD_NUMBER}"
              }
         }
     }
}
