
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: java-demoapp-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: demoapp  
  minReplicas: 2  
  maxReplicas: 10  
  metrics:
  - type: Pods
    pods:
      metricName: argo:applatency:histogram
      targetAverageValue: "1" 